export const cities = [
  "Warszawa",
  "Gdańsk",
  "Gdynia",
  "Sopot",
  "Bydgoszcz",
  "Łomianki",
  "Konstancin",
  "Pruszków",
  "Wołomin",
  "Mińsk Mazowiecki",
  "Nowy Dwór Mazowiecki",
  "Grodzisk Mazowiecki",
  "Piaseczno",
  "Ożarów Mazowiecki",
  "Otwock",
  "Legionowo",
  "Leszno",
  "Marki",
  "Reda",
  "Rumia",
  "Pruszcz Gdański",
  "Wejherowo",
  "Warzno",
  "Dobrzewino",
  "Tuchom",
  "Bojano",
  "Kielno",
  "Karczemki",
  "Miszewo",
  "Banino",
  "Rębiechowo",
  "Czaple",
  "Leźno",
  "Jankowo Gdańskie",
  "Kowale",
  "Straszyn",
  "Otomin",
  "Rotmanka",
  "Borkowo(gm.Pruszcz Gdański)",
  "Chwaszczyno",
  "Mosty",
  "Dębogórze",
  "Kosakowo",
  "Suchy Dwór",
  "Rewa",
  "Mechelinki",
  "Pierwoszyno",
  "Tczew",
  "Roszkowo",
  "Rokitnica",
  "Radunica",
  "Pepowo",
  "Stary Toruń",
  "Toruń ",
  "LUBICZ DOLNY",
  "LUBICZ GÓRNY",
  "ZŁOTORIA",
  "TURZNO",
  "GRĘBOCIN",
  "OSIEKI",
  "BRZOZÓWKA",
  "KROBIA",
  "KOPANINO",
  "GRABOWIE",
  "BRZOZA",
  "MAŁA NIESZAWKA",
  "WIELKA NIESZAWKA",
  "PRZYSIEK",
  "ROZGARTY",
  "BŁOTKA",
  "GÓRSK",
  "GUTOWO-LEŚNICTWO",
  "PĘDZEWO",
  "ZŁAWIEŚ WIELKA",
  "TOPORZYSKO",
  "CZARNOWO",
  "LULKOWO",
  "ŁYSOMICE",
  "PAPOWO TORUŃSKIE",
  "OSTASZEWO",
  "ZAKRZEWKO",
  "TYLICE",
  "GOSTKOWO",
  "KONICZYNKA",
  "LIPNICZKI",
  "TCZEW (!)",
  "BĄKOWO",
  "JUSZKOWO",
  "GŁĘBOKIE",
  "BYSEWO",
  "BABIE DOŁY",
  "CIECHOCINO",
  "Sulejówek",
  "Gługa Szlachecka",
  "Grabina",
  "Brzeziny",
  "Chobot",
  "Cisie",
  "Desno",
  "Długa Kościelana",
  "Halinów",
  "Hapolitów",
  "Józefin",
  "Kazimierów",
  "Królewskie Brzeziny",
  "Krzewina",
  "Mrówiska",
  "Nowy Konik",
  "Stary Konik",
  "Wielgolas Brzeziński",
  "Wielgołas Duchnowski",
  "Żwirowka",
  "Budziska",
  "Michałow",
  "Okuniew",
  "Ostrówik",
  "Zabraniec",
  "Zagórze ",
  "Hornówek",
  "Izabelin",
  "Izabelin B",
  "Izabelin C",
  "Klaudyn",
  "Koczargi Stare",
  "Laski",
  "Lipków",
  "Mościska",
  "Sieraków",
  "Truskaw",
  "Babice Nowe",
  "Blizne Jasińskiego",
  "Blizne Łaszczyńskiego",
  "Janów",
  "Koczargi Nowe",
  "Kwirynów",
  "Latchorzew",
  "Lubiczów",
  "Stare Babice",
  "Zielonki",
  "Zielonki-Parcela",
  "Zielonki-Wieś",
  "Borzęcin Duży",
  "Borzęcin Mały",
  "Buda",
  "Feliksów",
  "Ławy",
  "Mariew",
  "Stanisławów",
  "Topolin",
  "Wąsy-Kolonia",
  "Wąsy-Wieś",
  "Wierzbin",
  "Wiktorów",
  "Wojcieszyn",
  "Wólka",
  "Wyględy",
  "Zaborów",
  "Zaborówek",
  "Zalesie",
  "Białutki",
  "Czarnów",
  "Czarnów-Towarzystwo",
  "Grądy",
  "Julinek",
  "Korfowe",
  "Leszno",
  "Marianów",
  "Marianów",
  "Powązki",
  "Szadkówek",
  "Szymanówek",
  "Walentów",
  "Wilkowa Wieś",
  "Dawidy",
  "Dawidy Bankowe",
  "Falenty",
  "Falenty Duże",
  "Falenty Małe",
  "Janki",
  "Jaworowa",
  "Laszczki",
  "Łady",
  "Nowe Grocholice",
  "Podolszyn Nowy",
  "Puchały",
  "Raszyn",
  "Rybie",
  "Sękocin - Las",
  "Sękocin Nowy",
  "Sękocin Stary",
  "Słomin",
  "Wypędu",
  "Ząbki",
  "Dąbrowa",
  "Dziekanów Leśny",
  "Dziekanów Polski",
  "Izabelin-Dziekanówek",
  "Kępa Kiełpińska",
  "Kiełpin",
  "Kiełpin Poduchowny",
  "Łomianki",
  "Łomianki Dolne",
  "Nowy Dziekanów",
  "Sadowa",
  "Nowy Dwór Mazowiecki",
  "Nowy Dwór Mazowiecki",
  "Skierdy",
  "Suchocin",
  "Trzciany",
  "Wólka Górska",
  "Nowy Dwór Mazowiecki",
  "Bagno",
  "Jabłonna",
  "Rajszew",
  "Józefów",
  "Legionowo",
  "Łajski",
  "Michałów-Reginów",
  "Stanisławów Drugi",
  "Wola Aleksandra",
  "Legionowo",
  "Chotomów",
  "Dąbrowa Chotomowska",
  "Olszewica Stara",
  "Góra",
  "Janówek Pierwszy",
  "Kałuszyn",
  "Krubin",
  "Olszewica Nowa",
  "Poddębe",
  "Poniatów",
  "Sikory",
  "Skrzeszew",
  "Topolina",
  "Aleksandrów",
  "Beniaminów",
  "Białobrzegi",
  "Dąbkowizna",
  "Izabelin",
  "Kąty Węgierskie",
  "Michałow-Grabina",
  "Nieporęt",
  "Rembelszczyzna",
  "Stanisławów Pierwszy",
  "Wólka Radzymińska",
  "Zegrze Południowe",
  "Komornica",
  "Wieliszew",
  "Adamówek",
  "Augustówek",
  "Cybulice Duże",
  "Cybulice Małe",
  "Cząstków Mazowiecki",
  "Cząstków Polski",
  "Czeczotki",
  "Czosnów",
  "Dębina",
  "Janów-Mikołajówka",
  "Jesionka",
  "Kaliszki",
  "Kazuń Nowy",
  "Kazuń Polski",
  "Kazuń-Bielany",
  "Łomna",
  "Łomna-Las",
  "Łosia Wólka",
  "Palmiry",
  "Pieńków",
  "Sady",
  "Sowia Wola",
  "Sowia Wola Folwarczna",
  "Wólka Czosnowska",
  "Wrzosówka",
  "Zakroczym",
  "Pomiechowo",
  "Nowy Modlin",
  "Pomiechówek",
  "Stanisławowo",
  "Cięciwa",
  "Czarna",
  "Duczki",
  "Helenów",
  "Leśniakowizna",
  "Lipinki",
  "Majdan",
  "Nowe Lipiny",
  "Stare Lipiny",
  "Wołomin",
  "Zagościniec",
  "Zielonka",
  "Kobyłka",
  "Ossów",
  "Turów",
  "Cegielnia",
  "Ciemne",
  "Dybów-Kolonia",
  "Łąki",
  "Nowy Janków",
  "Radzymin",
  "Rżyska",
  "Sieraków",
  "Słupno",
  "Stary Janków",
  "Wiktorów",
  "Marki",
  "Nadma",
  "Arynów",
  "Kluki",
  "Barcząca",
  "Brzóze",
  "Budy Barcząckie",
  "Chmielew",
  "Chochół",
  "Choszczówka Stojecka",
  "Cielechowizna",
  "Cyganka",
  "Dłużka",
  "Dziękowizna",
  "Gamratka",
  "Gliniak",
  "Grabina",
  "Huta Mińska",
  "Iłówiec",
  "Karolina",
  "Kolonia Janów",
  "Królewiec",
  "Maliszew",
  "Marianka",
  "Mikanów",
  "Mińsk Mazowiecki",
  "Nowe Osiny",
  "Osiny",
  "Podrudzie",
  "Prusy",
  "Stara Niedziałka",
  "Stare Zakole",
  "Stojadła",
  "Targówka",
  "Tartak",
  "Wólka Mińska",
  "Zakole-Wiktorowo",
  "Zamienie",
  "Żuków",
  "Aleksandrów",
  "Bykowizna",
  "Cezarów",
  "Choszczówka Dębska",
  "Choszczówka Rudzka",
  "Chrośla",
  "Cięciwa",
  "Dębe Wielki",
  "Otwock",
  "Józefów",
  "Józefów",
  "Glina",
  "Okoły",
  "Pogorzel",
  "Samuszyn",
  "Boryszew",
  "Duchnów",
  "Dziechciniec",
  "Emów",
  "Góraszka",
  "Izabela",
  "Kąck",
  "Kopki",
  "Majdan",
  "Malcanów",
  "Michałowek",
  "Pęclin",
  "Radiówek",
  "Rudka",
  "Stefanówka",
  "Wiązowna",
  "Zagórze",
  "Żanęcin",
  "Brzezinka",
  "Glinki",
  "Janów  ",
  "Karczew",
  "Kępa Nadbrzeska",
  "Łukówiec",
  "Nadbrzeż",
  "Ostrówiec",
  "Otwock Mały",
  "Otwock Wielki",
  "Sobiekursk",
  "Władysławów",
  "Wygoda",
  "Chylice-Pólko",
  "Chyliczki",
  "Grochowa",
  "Jasówka",
  "Jastrzęcie",
  "Jazgarzew",
  "Józefosław",
  "Julianów",
  "Kierszki",
  "Łbiska",
  "Łoziska",
  "Mysiadło",
  "Nowa  Iwiczna",
  "Nowa Wola",
  "Pęchery",
  "Piaseczno",
  "Siedliska",
  "Stara Iwiczna",
  "Wólka Kozodowska",
  "Zabieniec",
  "Zamienie",
  "Zgorzała",
  "Jazgorzewszczyzna",
  "Piaseczno",
  "Bobrowiec",
  "Bogatki",
  "Gołków",
  "Kamionka",
  "Piaseczno",
  "Baszkówka",
  "Bąkówka",
  "Głosków",
  "Głosków-Letnisko",
  "Kuleszówka",
  "Mieszkowo",
  "Rabercin",
  "Wola Gołkowska",
  "Antoninów",
  "Runów",
  "Wólka Pracka",
  "Janczewice",
  "Lesznowla",
  "Magdalenka",
  "Podolszyn  ",
  "Wilcza Gówa",
  "Władysławów",
  "Brześce",
  "Czarnów",
  "Jastrzęcie",
  "Kierszki",
  "Konstancin-Jeziorna",
  "Bielawa",
  "Borowina",
  "Cieciszew",
  "Ciszyce",
  "Czernidła",
  "Dębówka",
  "Gassy",
  "Habdzin",
  "Kawęczyn",
  "Kawęczynek",
  "Kępa Oboeska",
  "Kępa Okrzewska",
  "Konstancin-Jeziorna",
  "Łęg",
  "Łyczyn",
  "Obory",
  "Obórki",
  "Okrzeszyn",
  "Opacz",
  "Piaski",
  "Porcele-Obory",
  "Słomczyn",
  "Turowice",
  "Dobiesz",
  "Góra Kalwaria",
  "Krzaki Czaplinowskie",
  "Kszymów",
  "Moczydłów",
  "Podłęcze",
  "Wojciechowice",
  "Wólka Dworska",
  "Góra Kalwaria",
  "Baniocha",
  "Chojnów",
  "Kąty  ",
  "Łubna",
  "Mikówiec",
  "Orzeszyn",
  "Pilawa",
  "Solec",
  "Szymanów",
  "Tomice",
  "Wólka Załąska",
  "Nowinki",
  "Ustanów",
  "Zalesie Górne",
  "Jabłonowo",
  "Łazy",
  "Marysin",
  "Stefanowo",
  "Walendów",
  "Kanie",
  "Otrębusy",
  "Granica",
  "Komorów",
  "Nowa Wieś",
  "Pęcice",
  "Pęcice Małe",
  "Sokołów",
  "Suchy Las",
  "Owczarnia",
  "Podkowa Leśna",
  "Terenia",
  "Żółwin",
  "Parzniew",
  "Michałowice-Osiedle",
  "Michałowice-Wieś",
  "Opacz Mała",
  "Opacz-Kolonia",
  "Pęcice",
  "Reguły",
  "Piastów",
  "Milanówek",
  "Kłudno Stare",
  "Odrano-Wola",
  "Adamów",
  "Chlebnia",
  "Chrzanów Duży",
  "Chrzanów Mały",
  "Grodzisk Mazowiecki",
  "Kady",
  "Kłudno Nowe",
  "Kozery",
  "Książenice",
  "Natolin",
  "Opypy",
  "Szczęsne",
  "Tłuste",
  "Urszulin",
  "Wólka Grodziska",
  "Żuków",
  "Grodzisk Mazowiecki",
  "Kajetany",
  "Nadarzyn",
  "Paszków",
  "Stara Wieś",
  "Strzeniówka",
  "Walendów",
  "Wolice",
  "Biskupice",
  "Brwinów",
  "Czubin",
  "Domaniew",
  "Domaniewek",
  "Falęcin",
  "Grudów",
  "Koszajec",
  "Kotowice",
  "Krosna-Parcela",
  "Krosna-Wieś",
  "Milęcin",
  "Moszna-Parcela",
  "Moszna-Wieś",
  "Bronisze",
  "Domaniewek Pierwszy",
  "Duchnice",
  "Gołaszew",
  "Jawczyce",
  "Kaputy",
  "Konotopa",
  "Koprki",
  "Macierzysz",
  "Mory",
  "Ołtarzew",
  "Ożarów Mazowiecki",
  "Piotrkówek Duży",
  "Piotrkówek Mały",
  "Pogroszew",
  "Strzykuły",
  "Szeligi",
  "Umiastów",
  "Wieruchów",
  "Józefów",
  "Myszczyn",
  "Orły",
  "Pilaszków",
  "Płochocin",
  "Święcice",
  "Wolskie",
  "Nowe Faszczyce",
  "Radzików",
  "Wola Łuszczewska",
  "Białuty",
  "Bieniewice",
  "Błonie",
  "Bramki",
  "Dębówka",
  "Górna Wieś",
  "Konstantów",
  "Kopytów",
  "Łaźniew",
  "Łaźniewek",
  "Nowa Górna",
  "Nowa Wieś",
  "Nowy Łuszczewek",
  "Pass",
  "Piorunów",
  "Radonice",
  "Rochaliki",
  "Rokitno",
  "Rokitno-Majątek",
  "Stare Faszczyce",
  "Stary Łuszczewek",
  "Wawrzyszew",
  "Witki",
  "Żukówka",
  "OTOROWO",
  "MAKOWISKA",
  "WYPALENISKA",
  "EMILIANOWO",
  "STRYSZEK",
  "BRZOZA",
  "OLIMPIN",
  "OLIMPIN-OSIEDLE",
  "PRZYŁĘDKI",
  "PRĄDKI",
  "ZIELONKA",
  "TRZCINIEC",
  "CIELE",
  "DĘBINEK",
  "BIAŁE BŁOTA",
  "LIPINKI",
  "KRUSZYN KRAJEŃSKI",
  "MUROWANIEC",
  "DRZEWCE",
  "LISI OGON",
  "ŁOCHOWO",
  "ŁOCHOWICE",
  "KRUSZYN",
  "KRUSZYNIEC",
  "MYŚLĘCINEK",
  "NIEMCZ",
  "OSIELSKO",
  "CZARNÓWCZYN",
  "STRZYŻAWA",
  "Tokary",
  "Miszewko",
  "Łódź",
  "Małkowo",
  "ŁOWICZ",
  "SKIERNIEWICE",
  "GŁOWNO",
  "ŁĘCZYCA",
  "PODDĘBICE",
  "UNIEJÓW",
  "ALEKSANDRÓW ŁÓDZKI",
  "KONSTANTYNÓW ŁÓDZKI",
  "ZGIERZ",
  "PABIANICE",
  "TUSZYN",
  "DĄBRÓWKA-STRUMIANY",
  "DĄBRÓWKA-MARIANKA",
  "DĄBRÓWKA-MALICE",
  "STARY IMIELNIK",
  "NOWE SKOSZEWY",
  "WÓDKA",
  "DĄBROWA",
  "TEOLIN",
  "BRZEZINY",
  "ADAMÓW",
  "KĘDZIORKI",
  "ROGÓW",
  "ROMANÓWEK",
  "FELICJANÓW",
  "KOLUSZKI",
  "GAŁKÓWEK",
  "GAŁKÓWEK-PARCELA",
  "GAŁKÓW-MAŁY",
  "JUSTYNÓW",
  "ANDRESPOL",
  "BEDOŃ PRZYKOŚCIELNY",
  "WIĄCZYŃ DOLNY",
  "WIŚNIOWA GÓRA",
  "GIEMZÓW",
  "LUDWIKÓW",
  "WYGODA",
  "LEŚNE ODPADKI",
  "KALINO",
  "KALINKO",
  "KALINKO-MORGI",
  "WOLA RAKOWA",
  "GRODZISKO",
  "RZGÓW",
  "RYDZYNKI",
  "PRAWDA",
  "STAROWA GÓRA",
  "KONSTANTYNA",
  "STARA GADKA",
  "NOWA GADKA",
  "BRONISIN DWORSKI",
  "PRZYPUSTA",
  "CZYŻEMINEK",
  "WOLA ZARADZYŃSKA",
  "SZYNKIELEW",
  "HERMANÓW",
  "BYCHLEW",
  "JADWININ",
  "RYDZYNY",
  "CHECHŁO DRUGIE",
  "PIĄTKOWISKO",
  "PERTYKOZY",
  "OKOŁOWICE",
  "USTRONIE",
  "WIKTORÓW",
  "EMILIA",
  "ROSANÓW",
  "LEONÓW",
  "OZORKÓW",
  "ALEKSANDRIA",
  "GORZEW",
  "MAJÓWKA",
  "PORSZEWICE",
  "PRUSINOWICZKI",
  "FLORENTYNÓW",
  "MIROSŁAWICE",
  "LUTOMIERSK",
  "WRZĄCA",
  "BECHCICE-WIEŚ",
  "WOLA GRZYMKOWA",
  "BUDY WOLSKIE",
  "PLACYDÓW",
  "ŁOBÓDŹ",
  "SŁOWAK",
  "ADOLFÓR",
  "KRZEMIEŃ",
  "GROTNIKI",
]
